Project-Files/controllerConfigTool/searchsalesorder/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,  SubmitField
from wtforms.validators import DataRequired



class SearchSalesOrderForm(FlaskForm):
    sales_order_number = StringField('Sales Order Number', validators=[DataRequired()])
    program_controllers = SubmitField('Program Controllers')
    edit_sales_order = SubmitField('Edit Sales Order')
    find_fans = SubmitField('Find All Fans')
    find_controllers = SubmitField('Find All Controllers in Systems Table')

Project-Files/controllerConfigTool/addressrangecreation/routes.py
'''CG Changes, This file is modified by CG developers on 07/04/2023'''

from flask import render_template, url_for, flash, redirect, request
from flask import Blueprint
from controllerConfigTool import app, db
from controllerConfigTool.models import SalesOrders
from controllerConfigTool.getInfoFromDatabase import findUnaddressedItems
from controllerConfigTool.addressrangecreation.forms import addressRangeCreationForm, addressRangeDisplayForm
from controllerConfigTool.addressrangecreation.utils import createFans, createFieldbusSensors, findaddressedItems
from controllerConfigTool.models import Job, FieldbusSensors
# import numpy as np



addressrangecreation_blueprint = Blueprint('addressrangecreation', __name__)


@addressrangecreation_blueprint.route('/address_range_display/<int:sales_order_id>', methods=['GET', 'POST'])
def address_range_display(sales_order_id):
    # pass
    sales_order_object = SalesOrders.query.filter_by(id=sales_order_id).first()
    default_mixer_fan_ending_address = sales_order_object.mixer_fan_quantity
    default_fieldbus_sensor_quantity = sales_order_object.fieldbus_sensor_quantity

    address_string_dictionary = findaddressedItems(sales_order_id)
    unaddressed_items_dict = findUnaddressedItems(sales_order_id)
    unaddressed_fbsensor_count = unaddressed_items_dict['Fieldbus Sensors']
    unaddressed_fans_count = unaddressed_items_dict['Fans']
    total_remaining_items = unaddressed_fbsensor_count + unaddressed_fans_count

    # create address range creation form
    address_range_edition_form = addressRangeDisplayForm(unaddressed_fans_count, unaddressed_fbsensor_count)
    # get existing addressed items
  
    

    if request.method == 'POST':
        if address_range_edition_form.validate_on_submit():

            if address_range_edition_form.edit_button.data:
                if total_remaining_items == 0:
                    return redirect(url_for('addressrangecreation.address_range_creation', sales_order_id=sales_order_id))
                else:
                    return redirect(url_for('addressrangecreation.address_range_creation', sales_order_id=sales_order_id))
            elif address_range_edition_form.return_button.data:
                    return redirect(url_for('salesorderstatus.salesorderstatusview', sales_order_id=sales_order_id))
        else:
            flash('Something Went Wrong', 'danger')

    return render_template('address_range_display.html', address_range_creation_form=address_range_edition_form, unaddressed_items_dict=unaddressed_items_dict,
                address_string_dictionary=address_string_dictionary)



@addressrangecreation_blueprint.route('/address_range_creation/<int:sales_order_id>', methods=['GET', 'POST'])
def address_range_creation(sales_order_id):
    # find sales order object
    sales_order_object = SalesOrders.query.filter_by(id=sales_order_id).first()
    entered_by = sales_order_object.input_by
    
    # find unassigned items
    unaddressed_items_dict = findUnaddressedItems(sales_order_id)

    unaddressed_fbsensor_count = unaddressed_items_dict['Fieldbus Sensors']
    # unaddressed_analog_count = unaddressed_items_dict['Analog Sensors']
    unaddressed_fans_count = unaddressed_items_dict['Fans']
    
    total_remaining_items = unaddressed_fbsensor_count + unaddressed_fans_count
    # Added condition and update the item dict for edit
    if total_remaining_items == 0:
        sales_order_object = SalesOrders.query.filter_by(id=sales_order_id).first()
        initial_mixer_fans_count = sales_order_object.mixer_fan_quantity
        initial_fieldbus_sensors_count = sales_order_object.fieldbus_sensor_quantity
        unaddressed_fans_count, unaddressed_fbsensor_count = initial_mixer_fans_count, initial_fieldbus_sensors_count
        unaddressed_items_dict['Fans'] = initial_mixer_fans_count
        unaddressed_items_dict['Fieldbus Sensors'] = initial_fieldbus_sensors_count
       
    default_mixer_fan_ending_address = sales_order_object.mixer_fan_quantity
    default_fieldbus_sensor_quantity = sales_order_object.fieldbus_sensor_quantity
    
    # create address range creation form
    address_range_creation_form = addressRangeCreationForm(unaddressed_fans_count, unaddressed_fbsensor_count)


    # get existing addressed items
    address_string_dictionary = findaddressedItems(sales_order_id)
    
    if request.method == 'POST':

        if address_range_creation_form.validate_on_submit():
            if address_range_creation_form.submit_button.data:
                
                mixer_fan_starting_address = address_range_creation_form.mixer_fan_starting_address.data
                mixer_fan_ending_address = address_range_creation_form.mixer_fan_ending_address.data
                fieldbus_sensor_starting_address = address_range_creation_form.fieldbus_sensor_starting_address.data
                fieldbus_sensor_ending_address = address_range_creation_form.fieldbus_sensor_ending_address.data
                # analog_sensor_starting_address = address_range_creation_form.analog_sensor_starting_address.data
                # analog_sensor_ending_address = address_range_creation_form.analog_sensor_ending_address.data
                # supply_exhaust_starting_address = address_range_creation_form.supply_exhaust_starting_address.data
                # supply_exhuast_ending_address = address_range_creation_form.supply_exhuast_ending_address.data
            
                # flash message boolean
                flash_message_boolean = False
                flash_message_string = ''

                # mixer fans
                submitted_mixerfan_count = 0
                if mixer_fan_starting_address is not None and mixer_fan_ending_address is not None:
                    submitted_mixerfan_count = mixer_fan_ending_address - mixer_fan_starting_address + 1
                    if submitted_mixerfan_count > unaddressed_fans_count:
                        flash(f'Invalid submission. You tried addressing {submitted_mixerfan_count} Mixer Fans while only {unaddressed_fans_count} Mixer Fans are available', 'danger')
                    else:
                        # get jobs number
                        sales_order_object = SalesOrders.query.filter_by(id=sales_order_id).first()
                        sales_order_number = sales_order_object.sales_order_number
                        # Added condition and sql query for deleting data previous data from database
                        if total_remaining_items == 0 and submitted_mixerfan_count <= unaddressed_fans_count:
                            Job.query.filter_by(sales_order_id=sales_order_id).delete()
                            db.session.commit()
                        # Create row for each Fan (in Jobs table)
                        createFans(sales_order_id, sales_order_number, mixer_fan_starting_address, mixer_fan_ending_address, entered_by)
                        flash_message_boolean = True
                        flash_message_string += f'Mixer Fans {mixer_fan_starting_address} - {mixer_fan_ending_address} were created. '


                # fieldbus sensors
                submitted_fieldbus_sensor_count = 0
                if fieldbus_sensor_starting_address is not None and fieldbus_sensor_ending_address is not None:
                    submitted_fieldbus_sensor_count = fieldbus_sensor_ending_address - fieldbus_sensor_starting_address + 1
                    if submitted_fieldbus_sensor_count > unaddressed_fbsensor_count:
                        flash(f'Invalid submission. You tried addressing {submitted_fieldbus_sensor_count} Fieldbus sensors while only {unaddressed_fbsensor_count} Fieldbus sensors are available', 'danger')
                    else:
                        # Added condition and sql query for deleting data previous data from database
                        if total_remaining_items == 0 and submitted_fieldbus_sensor_count <= unaddressed_fbsensor_count:
                            FieldbusSensors.query.filter_by(sales_order_id=sales_order_id).delete()
                            db.session.commit()
                        # Create row for each Fieldbus sensor (in Fieldbus Sensors table)
                        createFieldbusSensors(sales_order_id, fieldbus_sensor_starting_address, fieldbus_sensor_ending_address)
                        flash_message_boolean = True
                        flash_message_string += f'Fieldbus Sensors {fieldbus_sensor_starting_address} - {fieldbus_sensor_ending_address} were created. '


                # analog sensors
                # submitted_analog_sensor_count = 0
                # if analog_sensor_starting_address is not None and analog_sensor_ending_address is not None:
                #     submitted_analog_sensor_count = analog_sensor_ending_address - analog_sensor_starting_address + 1
                #     if submitted_analog_sensor_count > unaddressed_analog_count:
                #         flash(f'Invalid submission. You tried addressing {submitted_analog_sensor_count} Analog sensors while only {unaddressed_analog_count} Analog sensors are available', 'danger')
                #     else:
                #         # Create row for each Analog sensor (in Analog Sensors table)
                #         createAnalogSensors(sales_order_id, analog_sensor_starting_address, analog_sensor_ending_address)
                #         flash_message_boolean = True
                #         flash_message_string += f'Analog Sensors {analog_sensor_starting_address} - {analog_sensor_ending_address} were created. '


                # supply exhuast fans
                # submitted_exhaust_supply_fan_count = 0
                # if (supply_exhaust_starting_address is not None and supply_exhuast_ending_address is not None):
                #     submitted_exhaust_supply_fan_count = submitted_exhaust_supply_fan_count + (supply_exhuast_ending_address-supply_exhaust_starting_address + 1)

Project-Files/controllerConfigTool/salesorder/routes.py
from flask import render_template, url_for, flash, redirect, request
from flask import Blueprint

from controllerConfigTool import db, app
from controllerConfigTool.models import ControllerProgramStatus, SalesOrders, Controller, ControllerInputOutputs,Zone, OutputZones
from controllerConfigTool.createFans import createExpansionBoards
from controllerConfigTool.createSensors import createAnalogSensors
from controllerConfigTool.getInfoFromDatabase import findFirstNonConfiguredController,\
     getSelectedVersion, getSettingsID, getDateAndTime
from controllerConfigTool.salesorder.forms import SalesOrderForm

from controllerConfigTool.models import Settings
from controllerConfigTool.admin.utils import saveVersionSelection



salesorder_blueprint = Blueprint('salesorder', __name__)

@salesorder_blueprint.route('/', methods=['GET', 'POST'])
@salesorder_blueprint.route("/createsalesorder/", methods=['GET', 'POST'])


# def currentdisplayversion():
#     display_version = Settings.query.filter_by(currently_selected = True).first()
#     # print("------------------------------",display_version,  type(display_version),"------------------------------------")
#     display_version = str(display_version)
#     return display_version


def createsalesorder():

    # find selected software version
    selected_version = getSelectedVersion()
    # find corresponding id
    settings_id = getSettingsID()

    sales_order_form = SalesOrderForm()

    if request.method == 'POST':
        # when submit button is pressed, if form data is valid
        if sales_order_form.validate_on_submit():

            order = SalesOrders(
                sales_order_number=sales_order_form.sales_order_number.data,
                time_zone=sales_order_form.time_zone.data,
                controller_quantity=sales_order_form.controller_quantity.data,
                mixer_fan_quantity=sales_order_form.mixer_fan_quantity.data,
                fieldbus_sensor_quantity=sales_order_form.fieldbus_sensor_quantity.data,
                analog_sensor_quantity=sales_order_form.analog_sensor_quantity.data,
                expansion_board_quantity=sales_order_form.expansion_board_quantity.data,
                fieldbus_drives_quantity=sales_order_form.fieldbus_drives_quantity.data,
                tag_name=sales_order_form.tag_name.data,
                input_by=sales_order_form.entered_by.data, 
                input_on=getDateAndTime()
                )
            db.session.add(order)
            db.session.commit()

            # CG CHANGES 23/03/2023 to update software version in settings table start
            select_version= sales_order_form.software_version.data
            saveVersionSelection(select_version)
            # end


            flash(f'Sales Order data saved into database for order {sales_order_form.sales_order_number.data}!', 'success')

            sales_order_object = SalesOrders.query.filter_by(sales_order_number = sales_order_form.sales_order_number.data).first()
            sales_order_controller_quantity = sales_order_object.controller_quantity
            sales_order_id = sales_order_object.id
            tag_prefix = sales_order_form.tag_name.data

            print("-------",sales_order_id, "-------", tag_prefix,"-----", select_version)

            # Initialize rows in Controller table
            for item in range(0, sales_order_controller_quantity):
                controller = Controller(
                                        sales_order_id=sales_order_id, tag_name=tag_prefix + str(item + 1), version_number_id=select_version
                                        )
                db.session.add(controller)

            db.session.commit()

            controller_objects = Controller.query.filter_by(sales_order_id=sales_order_id).all()
            for controller_object in controller_objects:
                controller_input_output = ControllerInputOutputs(
                                            sales_order_id = controller_object.sales_order_id,
                                            controller_id = controller_object.id 
                                            )
                controller_program_status_object = ControllerProgramStatus(
                    controller_id = controller_object.id
                )

                zone_obj= Zone(sales_order_id=sales_order_id, controller_id=controller_object.id)
                db.session.add(zone_obj)

                ouput_zones = OutputZones(sales_order_id=sales_order_id, controller_id = controller_object.id)
                db.session.add(ouput_zones)


                db.session.add(controller_input_output)
                db.session.add(controller_program_status_object)


            db.session.commit()

            # create expansionboards for the given sales order id
            createExpansionBoards(sales_order_id, sales_order_form.expansion_board_quantity.data)

            # create row for each analog sensor in analog_sensors table
            # send 0 to start w/ address 1 
            createAnalogSensors(sales_order_id, sales_order_form.analog_sensor_quantity.data, 0)

            current_controller = findFirstNonConfiguredController(sales_order_id, tag_prefix)

            # if user wants to choose directory for archiving files
            file_path_boolean = sales_order_form.file_path_boolean.data
            if file_path_boolean:
                return redirect(url_for('choosefilepath.redirectchoosefilepath_', sales_order_id=sales_order_id, 
                                tag_prefix=tag_prefix, current_controller=current_controller, root_directory=app.config['ARCHIVE_ROOT_DIRECTORY']))
            else:
                return redirect(url_for('addressrangecreation.address_range_creation', sales_order_id=sales_order_id
                                    )) 
        else:
            flash('Sales Order data failed to save to database', 'danger')

    return render_template('salesorder.html', title='New Sales Order', sales_order_form=sales_order_form, selected_version=selected_version)

Project-Files/controllerConfigTool/templates/addfans.html
{% extends "layout.html" %}
{% block content %}
    <head>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css">

        <style>
            .card {
                margin-bottom: 0rem;
                border-width: 0.15rem;
                border-color: black;

            }
            .card-header {
                background-color:rgb(179, 179, 179);
                font-size: 1.5rem;
                font-weight: bold;
                padding: .25rem 1.25rem;
            }
            .card-body {
                background-color: rgb(230, 230, 230);
                padding: 0.5rem;
            }
            .content-section {
                border-width: 0.1rem;
                border-color: black;
            }
            #modbus_address_count{
                width: 4rem;
                margin-left: 1rem;
            }
            .form-group {
                margin-bottom: 0rem;
            }
            #footer {
                position: absolute;
                bottom: 0;
                width: 100%;
                height: 2.5rem;  
            }
        </style>

    </head>

    <div class="container">

        <div class="row">
            <div class="col-md-6">
                <h3>Insert Fan Address Ranges</h3>
            </div>
        </div>

        <form method="POST" action="">
            {{ insert_mixer_fan_addresses_form.csrf_token }}

            <fieldset class="form-group">

                <div class="row">
                    <div class="col-md-6">
    
                        <div class="card">
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-md-7">
                                        Fan Range 1
                                    </div>
                                    <div class="col-md-5">
                                        Available: {{ unassigned_fans }}
                                    </div>
                                </div>
                                
                            </div>
                            <div class="card-body">
                                <!-- mixer fan ranges row -->
                                <div class="row">
                                    <div class="col-6">
                                        {{ insert_mixer_fan_addresses_form.fan_range_1_starting_address.label(class="form-control-label") }}
                                        {% if insert_mixer_fan_addresses_form.fan_range_1_starting_address.errors %}
                                            {{ insert_mixer_fan_addresses_form.fan_range_1_starting_address(class="form-control form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in insert_mixer_fan_addresses_form.fan_range_1_starting_address.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ insert_mixer_fan_addresses_form.fan_range_1_starting_address(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>
                                    <div class="col-6">
                                        {{ insert_mixer_fan_addresses_form.fan_range_1_ending_address.label(class="form-control-label") }}
                                        {% if insert_mixer_fan_addresses_form.fan_range_1_ending_address.errors %}
                                            {{ insert_mixer_fan_addresses_form.fan_range_1_ending_address(class="form-control form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in insert_mixer_fan_addresses_form.fan_range_1_ending_address.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ insert_mixer_fan_addresses_form.fan_range_1_ending_address(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
    
                    </div>
                    
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <!-- submit button -->
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-10"></div>
                                <div class="col-md-2">
                                    {{ insert_mixer_fan_addresses_form.submit(class="btn btn-primary") }}
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
    
            </fieldset>

        </form>

        



        

        
    </div>
    

    
    
{% endblock %}

Project-Files/controllerConfigTool/templates/displaycontrollers.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">

        <legend class="border-bottom mb-4">Controllers for Sales Order: {{ sales_order_number }}</legend>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Row #</th>
                    <th scope="col">Job Number</th>
                    <th scope="col">Entered On</th>
                    <th scope="col">Fan 1</th>
                    <th scope="col">Programmed</th>
                </tr>
            </thead>
            <tbody>
                {% for row_index, job_number, entered_on, fan_1, programmed in controller_data%}
                    <tr>
                        <th scope="row">{{ row_index }}</th>       
                        <td>{{ job_number }}</td>
                        <td>{{ entered_on }}</td>
                        <td>{{ fan_1 }}</td>
                        <td>{{ programmed }}</td>
                    </tr>

                {% endfor %}       
            </tbody>

        </table>
               
      
    </div>
{% endblock %}

Project-Files/controllerConfigTool/templates/displayfans.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">

        <legend class="border-bottom mb-4">Fans for Sales Order: {{ sales_order_number }}</legend>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Row #</th>
                    <th scope="col">Job Number</th>
                    <th scope="col">Address</th>
                    <th scope="col">Number of Sensors</th>
                    <th scope="col">Command Value</th>
                    <th scope="col">Max Speed</th>
                    <th scope="col">Fan Type</th>
                </tr>
            </thead>
            <tbody>
                {% for row_index, job_number, address, number_of_sensors, command_value, max_speed, fan_type in fan_data %}
                    <tr>
                        <th scope="row">{{ row_index }}</th>       
                        <td>{{ job_number }}</td>
                        <td>{{ address }}</td>
                        <td>{{ number_of_sensors }}</td>
                        <td>{{ command_value }}</td>
                        <td>{{ max_speed }}</td>
                        <td>{{ fan_type }}</td>
                    </tr>

                {% endfor %}       
            </tbody>

        </table>
               
      
    </div>
{% endblock %}

Project-Files/controllerConfigTool/templates/layout_container_fluid.html
{% from 'bootstrap/nav.html' import render_nav_item %}
{% from 'bootstrap/utils.html' import render_messages %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {{ bootstrap.load_css() }}
    <style>
      .currently_selected {
        font-size: 1.5rem;
        font-weight: bold;
        color: white !important;
      }
      .content-section {
                border-width: 0.1rem;
                border-color: black;
      }
      #footer {
        position: relative;
        bottom: 0;
        width: 100%;
        height: 2.5rem;  
      }
        
      #page-container {
        position: relative;
        min-height: 100vh;
      }
      .navbar{
        margin-bottom: 50px !important;
      }
      .card {
                margin-bottom: 1rem;
                border-width: 0.15rem;
                border-color: black;
      }

    </style>

    {% if title %}
        <title>ZOO Fans Web App - {{ title }}</title>
    {% else %}
        <title>ZOO Fans Web App</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-primary navbar-static-top">
        <div class="container-fluid">
          <div class="navbar-nav">
            {% if title=='Configure Sales Order' %}
            <a class="nav-item nav-link currently_selected" href="{{ url_for('salesorder.createsalesorder') }}">New Sales Order</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('salesorder.createsalesorder') }}">New Sales Order</a>
            {% endif %}
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav">
              {% if title=='Edit Controllers' %}
              <a class="nav-item nav-link currently_selected" href="{{ url_for('searchsalesorder.searchsalesordernumber', view_state='edit_sales_order') }}">Edit Sales Order</a>  
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('searchsalesorder.searchsalesordernumber', view_state='edit_sales_order') }}">Edit Sales Order</a>  
              {% endif %}                       
            </div>
            <div class="navbar-nav">
              {% if title=='Program Controllers' %}
              <a class="nav-item nav-link currently_selected" href="{{ url_for('searchsalesorder.searchsalesordernumber', view_state='program_controller') }}">Program Controllers</a> 
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('searchsalesorder.searchsalesordernumber', view_state='program_controller') }}">Program Controllers</a> 
              {% endif %}
            </div>
            <!-- <div class="justify-content-end"> -->
              <div class="navbar-nav">
                {% if title=='Search Database' %}
                <a class="nav-item nav-link currently_selected" href="{{ url_for('searchsalesorder.searchsalesordernumber', view_state='find_fans') }}">Search Database</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('searchsalesorder.searchsalesordernumber', view_state='find_fans') }}">Search Database</a>
                {% endif %}
              </div>
              <div class="navbar-nav ml-auto">
                {% if title=='Select Version' %}
                <a class="nav-item nav-link currently_selected" href="{{ url_for('admin.selectversion', view_state='Select Version') }}">Select Version</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('admin.selectversion', view_state='Select Version') }}">Select Version</a>
                {% endif %}
              </div>
            

          </div>

        </div>
      </nav>
    </header>
    <main class="container-fluid" id="page-container">
      <div id="content-wrap">
        <div id="alert">
          {{ render_messages(container=False, dismissible=True) }}
        </div>
        <div class="row">
          <div class="col-md-1">
            
          </div>
          <div class="col-md-10">
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-1">
            
          </div>
        </div>
        
      </div>

      <!-- <footer class="text-center" id="footer">
        {% block footer %}
            <small> &copy; ZOO Fans - EC Fan Controller Configuration Tool v1.9</a>
            </small>
        {% endblock %}
      </footer> -->
    </main>

          


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

Project-Files/controllerConfigTool/templates/salesorder_controllers_finished.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section col-md-6">
    Sales Order: {{ sales_order_number }}

</div>



{% endblock content %}